name: examples
version: 0.1.0.0
github: "Arkham/examples"
license: BSD3
author: "Ju Liu"
maintainer: "liuju86@gmail.com"
copyright: "Copyright (c) Ju Liu"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Arkham/examples#readme>

dependencies:
  - base >= 4.7 && < 5
  - random >= 1.1
  - containers >= 0.6
  - text >= 1.2.3.1

library:
  source-dirs: src

executables:
  examples-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - examples
  file-counts-exe:
    main: FileCounts.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is FileCounts
    dependencies:
      - examples

tests:
  examples-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - examples
